name: Gold Nugget Pictures
favicon: null
layout_spectrum: 0.7816311742644757
typography_spectrum: 0.6907383785583079
title: Pictures of Gold Nuggets from around the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#ac7c00'
    - '#a4a795'
    - '#ffffa0'
    - '#3d422d'
  brandStrength: 0.5
  lightness: 0.07294745836406946
  saturation: 0.7825064659118652
  rhythmicContrast: 0.6651379386894405
purpose: []
